# Generated by Django 3.1.1 on 2020-09-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampleApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='fontsize',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
